### ISSUE TITLE
add excluded intervals to M2 wdl

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1032]
@takutosato did you say you were already doing this?

**Comment by takutosato** [comment]
@davidbenjamin I ended up not adding it to the WDL because the dream WGS jobs finished in about 5 hours scattered 200 ways.

We could add it as another parameter to the workflow. But I think it's cleaner to add one string parameter, say extra_command_line_arguments, where we specify one or more arguments e.g. "-XL exclude1.vcf -XL exclude2 --STRAND_ARTIFACT_POSTERIOR_PROB_THRESHOLD 0.9". What do you think?

**Comment by davidbenjamin** [comment]
Hmmm, I need to think about that.

**Comment by davidbenjamin** [comment]
@takutosato I am persuaded; your way is the cleanest option.  I implemented this in a branch that cleans the hapmap wdl, which will be a PR soon.
