### ISSUE TITLE
Be more discriminating about soft clips in active region determination

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#1094]
In active region determination for Mutect, and I believe also HaplotypeCaller, we count soft clips as a potential sign of a variant.  This is because the aligner might soft clip the last few bases of a read that follow a deletion rather than call the deletion.  For example, if the reference and read are:

TTCCAGAGTGTGTCAC (reference)
TTC____________GTCAC (read)

the alignment might choose to soft clip the GTCAC rather than call a deletion on the CAGAGTGT.

In somatic calling it is expensive to call too many active regions, so perhaps we should only count eg the soft-clipped bases GTCAC as evidence of variation if that kmer appears downstream in the reference.

@fleharty is this understanding of soft-clips being possible deletions (but not insertions or SNVs) correct?

**Comment by fleharty** [comment]
@davidbenjamin 

I certainly agree with you that soft-clips can be due to deletions.  It's not at all clear to me that they wouldn't happen with an insertion.  Consider:

---ATGAACAGATATAACAGAT (reference)
---ATGAA(AGGTAA)CAGATATAACAGAT (read)

I don't see why a soft clip might not show up on this read after ATGAA.
I'm not really sure I understand why some things are soft-clipped to be honest.  I've seen plenty of things that were soft-clipped, but appear to match the reference perfectly (maybe I'm remembering this incorrectly).

I suspect that soft-clips are hardly ever correctly associated with SNVs though.

**Comment by davidbenjamin** [comment]
@fleharty Thanks for the input!

**Comment by ldgauthier** [comment]
You'll also likely see a difference in behavior for exomes vs genomes
because exomes (still) use bwa-aln and genomes use bwa-mem. I don't
remember the details off the top of my head, but I looked into it for
monkol at one point when he saw what he thought was a suspicious proportion
of soft clips in his data.

---------------------------------------
Laura Doyle Gauthier, PhD
Computational Biologist
Data Sciences and Data Engineering
Broad Institute of MIT and Harvard
gauthier@broadinstitute.org

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #3014](https://github.com/broadinstitute/gatk/issues/3014) via [**ZenHub**](https://www.zenhub.com/)
