### ISSUE TITLE
Make segmenter sample name parameter optional

### ISSUE THREAD

**Issue by achevali** [broadinstitute/gatk-protected#133]
Check that contig start stop name are in the colnames or fail
If only one remaining colname use that as sample name if none specified
If multiple colnames remaining fail if no sample name specified

**Comment by LeeTL1220** [comment]
This needs to bumped up in priority since it leads to issues in evaluations, even on Broad bams (though it seems to only affect Broad bams in the cloud)

@dlivitz and myself ran into issues when the bam filename did not match the sample name in the header.

Solution will be to automatically determine the sample name from the input file and feed that to the segmenter.

**Comment by LeeTL1220** [comment]
Plan to update the following CLIs: 

- [ ] CallSegments
- [ ] PerformSegmentation
- [ ] PlotSegmentedCopyRatio
- [ ] PlotSegmentedAllelicFraction

- [ ] update the forum docs.

AllelicCNV looks like it does not need an update.
