### ISSUE TITLE
Determine correct copy-ratio model for ACS given output from GATK CNV.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#215]
@kareembroad has been looking into the distribution of residuals (difference between coverage and segment mean) from CBS.  We should adjust the copy-ratio model in ACS according to what he finds for samples run through the best-practices GATK CNV workflow.

The issue is that we'd like to model the coverages in each segment by a normal distribution.  It is not clear whether this should be done in log space or if the variance of the normal distribution scales linearly with segment mean.  The answer may depend on whether or not logged quantities were passed to CBS.

**Comment by kareembroad** [comment]
@LeeTL1220 Hi Lee. The images I presented at lab meeting were made using CLL data that Amaro gave me. I used this because it's clean and highly curated. I figure you might know better what version of ReCapSeg Amaro used and whether the values passed to segmenter in that version were in log space or not. (Based on the fact that when I compute the means of the targets it's almost always identical to the segment mean, I am pretty sure the segmenter did NOT get the data in log space.)

**Comment by samuelklee** [comment]
After talking with @kareembroad, it seems that the copy-ratio model currently implemented is correct.  Note that this model differs from the python/previous versions in that the standard deviation of the log coverages in each segment does NOT scale linearly with the segment mean.
