### ISSUE TITLE
Are we confusing bed files and target files?

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#277]
There seem to be some areas of the code that use BED files (e.g. NormalizeSomaticReadCounts) and others that do not ...  Is this being consistent across the tools?

**Comment by vruano** [comment]
Currently the only place we are really force to use a BED is when we need to use as an interval file -L in GATKtools, otherwise I think the tab-table format with headers is preferable and we should move to use that all the time. 

I think at some point I discussed with @droazen that it would be nice to be able to use any feature/locatable containing file a as interval file but I don't think it was considered priority at the time and I guess is not there yet.

**Comment by samuelklee** [comment]
This is mostly addressed, with the exception of AnnotateTargets (see #645).
