### ISSUE TITLE
Should ExcessHet be computed for 1 sample?

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#464]
in Gatk3.4.36 InbreedingCoeff was not computed for 1 sample. we compute ExcessHet for 1 sample (where it's clearly bogus). 

@meganshand what's the gatk3.5 minumum sample count for ExcessHet?

**Comment by meganshand** [comment]
There's no minimum. It's not bogus, just not very informative. For one sample it always returns a p-value of .5 (which I think is reported as a phred-scaled p-value). This is so that it can still be computed for small sample sizes without worrying about a cutoff, but it won't be filtered out until the sample size is large enough to detect a problem.

**Comment by akiezun** [comment]
ok. works as designed then. Thanks @meganshand
