### ISSUE TITLE
ACNV without paired normal

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#56]
[Based on conversation with Adam] Gaddy has a lot of tumor-only FFPE samples that AllelicCapSeg can't handle.  It shouldn't be too hard to look up het sites from an external database rather than from a matched normal.  The model math would also change a bit.

**Comment by akiezun** [comment]
Note for the implementer. It may be beneficial to take 2 things into account:
- population frequencies of SNPs are known (up to population of origin but the set of possible freqs is still limited) so you have a prior on how much you think a given SNP is there or not
- SNPs (particularly common ones) that are close by (up to megabases away actually) are correlated, sometimes highly correlated (LD). The HapMap has a database of correlation coefficients between SNPs. That means you can borrow statistical strength in the the whole haplotype block because once you see SNP x then SNP y is highly likely if x and y are highly correlated. You can often highly-accurately impute (and there's a ton of work and software for it) the presence or absence of a SNP given other snps.

**Comment by mbabadi** [comment]
Hi Adam, thanks for your thoughts. In fact, I have been considering both tricks for the next round of ideas to include in my implementation. However, I expect to get little more mileage from these just because a flat Het SNP prior + a simple local decision rule (without considering long-range correlations) already yields ~ 95% concordance with paired-normal Het pulldown.
