### ISSUE TITLE
Git branch of gatk 

### ISSUE THREAD

**Issue by virtuabhi** [broadinstitute/gatk-protected#730]
Hi, 

I am interested in doing development work on gatk and gatk-protected. I have modified the build.gradle file in gatk-protected to use the gatk jars generated in my local gatk/build/libs directory.

However, I am getting build errors in gatk-protected (while the unmodified gradle file, which downloads gatk jars from https://artifactory.broadinstitute.org/artifactory/libs-snapshot/org/broadinstitute/gatk/4.alpha.1-199-g8377acb-SNAPSHOT/ builds successfully).

I think it might be due to version compatibility issues between the current master branches in gatk-protected and gatk.

Can some one point to a working pair version/branch for gatk-protected and gatk? Or, if I am missing some obvious steps?

Thanks
Abhishek

**Comment by droazen** [comment]
Yes, it's been a little while since we updated gatk-protected's dependency on gatk due to some refactoring in the read filtering framework. I'll open a PR shortly to bring it up to date with the latest gatk master.

When working with both gatk and gatk-protected locally, you shouldn't have to hack `build.gradle` to manually point protected at your gatk jars. Instead, you can run `./gradlew install printVersion` in gatk, which will install a gatk snapshot to your local maven repository and print the version of the snapshot at the end. Then you can just depend on that snapshot version in your gatk-protected `build.gradle`, and it will pull it from your maven local repository.

**Comment by virtuabhi** [comment]
Thanks a lot.

I got gatk-protected working with gatk (12th July commit d418b68).

The method of using local maven repository is neat too.
