### ISSUE TITLE
TandemRepeat annotation sometimes doesn't do its job

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk-protected#963]
Sometimes (*but not always*) the `TandemRepeat` annotation fails to get triggered, for example CCT (ref) -> C (alt) in a context of CCTCTCTCT.  There is a comment saying `Caveat: This annotation is currently not compatible with HaplotypeCaller`.  @vruano @ldgauthier do you know anything about this?

This is very important for Mutect because without the STR contraction filter our indel false positive rates are much higher than they should be.

**Comment by ldgauthier** [comment]
It's short work to make it HC compatible. I did the hard work a while ago
for m2. Didn't realize there were cases being missed, but I didn't touch
the algorithm. It could definitely be improved.

---------------------------------------
Laura Doyle Gauthier, PhD
Computational Biologist
Data Sciences and Data Engineering
Broad Institute of MIT and Harvard
gauthier@broadinstitute.org

On Mar 30, 2017 2:11 AM, "David Benjamin" <notifications@github.com> wrote:

Sometimes (*but not always*) the TandemRepeat annotation fails to get
triggered, for example CCT (ref) -> C (alt) in a context of CCTCTCTCT.
There is a comment saying Caveat: This annotation is currently not
compatible with HaplotypeCaller. @vruano <https://github.com/vruano>
@ldgauthier <https://github.com/ldgauthier> do you know anything about this?

This is very important for Mutect because without the STR contraction
filter our indel false positive rates are much higher than they should be.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/broadinstitute/gatk-protected/issues/963>, or mute the
thread

**Comment by davidbenjamin** [comment]
Was your work forward-ported to GATK 4?  In the git history for `TandemRepeat.java` I see nothing besides Adam's original port of the code in 2015.

**Comment by ldgauthier** [comment]
It looks like I didn't update the doc string about HC compatibility until
after Adam's port, but it was a teensy commit (
https://github.com/broadinstitute/gsa-unstable/commit/7727c0daa4428498d0c1d390e6f4fe6608c5dd8c).
I believe the functional changes I made were ported, which makes sense if
you're getting any output at all.  :) (The ActiveRegion special cases are
gone and the class name changed, but that's all for the better.) I remember
thinking the repeat unit finder isn't very efficient and really hurts the
performance, but that's just anecdotal evidence from years ago in GATK3.
It would be nice to have a good algorithm because we do something similar
(and similarly inefficient) when we do the indel likelihood model for the
GVCF reference confidence calculation, which Valentin has pointed out in
the past.

**Comment by davidbenjamin** [comment]
Submitted a PR to fix this in gatk public.  @ldgauthier It seems like the issue was that`TandemRepeat` was checking the bases from `ReferenceContext::getForwardBases`, which assumes that the `ReferenceContext`'s interval starts at the same place as the `VariantContext`, which is often not true.

**Comment by ldgauthier** [comment]
Good catch!

**Comment by davidbenjamin** [comment]
Closed by PR #973.
