### ISSUE TITLE
Docker tests increased wall-clock time of the test suite by 30%+

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk-protected#977]
The docker tests take about 40 minutes in travis, while the next-slowest travis task takes about 30 minutes. We should try to reduce the runtime of the docker tests to <= 30 minutes.

**Comment by droazen** [comment]
For @LeeTL1220

**Comment by LeeTL1220** [comment]
I thought we were going to address this with a GATK base image...  what is
target time?  (Within reason)

On Apr 5, 2017 20:08, "droazen" <notifications@github.com> wrote:

For @LeeTL1220 <https://github.com/LeeTL1220>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/broadinstitute/gatk-protected/issues/977#issuecomment-292032382>,
or mute the thread

**Comment by droazen** [comment]
That is tracked at https://github.com/broadinstitute/gatk/issues/2457 and slated for beta (mid-May). This ticket in protected can be considered as blocked until https://github.com/broadinstitute/gatk/issues/2457 is done.

**Comment by droazen** [comment]
Issue moved to [broadinstitute/gatk #2965](https://github.com/broadinstitute/gatk/issues/2965) via [**ZenHub**](https://www.zenhub.com/)
