### ISSUE TITLE
Add warning/exception when target/BED files are misused

### ISSUE THREAD

**Issue by dpmccabe** [broadinstitute/gatk-protected#985]
There have been a few occasions when I've gotten tripped up by GATK's expectation of a Picard-style target file (1-based, closed intervals) instead of a standard BED file (0-based, half-open intervals) for tools like `PadTargets` and `CalculateTargetCoverage`.

For instance, `PadTargets` doesn't seem to consider the half-openness of the format when adding the specified amount of padding causes two intervals to overlap:

```
> cat test.bed
contig	start	stop	name
1	100	200	chr1-a
1	250	350	chr1-b

> java -jar /gatk-protected.jar PadTargets -T test.bed -O test.padded.bed --padding 75

> cat test.padded.bed
contig	start	stop	name
1	25	225	chr1-a
1	226	425	chr1-b
```

This *does not* contain the 0-based position 225 (a.k.a. chr1:226 if you're using IGV). If you arbitrarily add that position back to one of the intervals (i.e. `1 25 226`), `CalculateTargetCoverage` will raise an exception about overlapping intervals, despite this being a completely valid BED file.

Granted, both tools do ask for a "target" file, but it's not clear that they mean a Picard-style list of intervals. I suspect many people are using BED files instead, including our very own @LeeTL1220 in the [CNV workflow instructions](http://gatkforums.broadinstitute.org/gatk/discussion/6791/description-and-examples-of-the-steps-in-the-cnv-case-and-cnv-pon-creation-workflows#create-pon-workflow).

Maybe he read [this FAQ](http://gatkforums.broadinstitute.org/gatk/discussion/1319/collected-faqs-about-interval-lists), which claims that the GATK should automatically convert these intervals as needed. So, there's apparently some confusion about whether any of this actually _should_ work.

I don't mind converting the BED file because it's easy and 0-based indexing is stupid (although `ConvertBedToTargetFile` doesn't seem to work—I'll submit a separate issue), but I think either the BED file should be converted internally or a warning/exception should be raised if that behavior is too opinionated.

**Comment by samuelklee** [comment]
Right, these tools expect a 1-based Picard interval list with the appropriate column headers (which is called the "target file format" in some of the documentation), not 0-based BED files.  If one has targets specified by a BED file, the expectation is that the output of ConvertBedToTargetFile will be passed to these tools.  I agree that the documentation could be more clear.

Additional confusion arises because a 1-based Picard interval list could also be a valid BED file if it ends with the "bed" extension (according to the BED codec).  One partial solution is for TargetCodec to disallow files ending with the "bed" extension.  Although this doesn't remove all possible sources of confusion, it should fix the issue you encountered in #986.
